apiVersion: v1
kind: Service
metadata:
  name: svc-first-deployment
  namespace: default
spec:
  selector:
    app: first-deployment
  ports:
  - name: nginx
    port: 80
  - name: multitool
    port: 8080
  type: ClusterIP
