apiVersion: apps/v1
kind: Deployment
metadata:
  name: first-deployment
  labels:
    app: first-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: first-deployment
  template:
    metadata:
      labels:
        app: first-deployment
    spec:
      containers:
      - image: nginx:1.19
        name: nginx
        imagePullPolicy: IfNotPresent
        ports:
        - name: nginx
          containerPort: 80
      - image: wbitt/network-multitool
        name: multitool
        imagePullPolicy: IfNotPresent
        ports:
        - name: multitool
          containerPort: 8081
