apiVersion: v1
kind: Pod
metadata:
  labels:
    app: multitool
  name: multitool
  namespace: default
spec:
  containers:
  - name: multitool
    image: wbitt/network-multitool
    ports:
    - containerPort: 8080